### ISSUE TITLE
Add a very visible note about change in YAML: rjournal_article

### ISSUE THREAD

**Issue by dicook** [rjournal/rjtools#112]
rjournal_article will Redner both html and pdf

rjournal_web_article only the html

rjournal_pdf_article only the pdf

This is going to create a headache for current authors because rjournal_web_article generate dual output.

**Comment by dicook** [comment]
AND make sure create_article generates the appropriate YAML:

```
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
```
