### ISSUE TITLE
Broken check: `detect_bib`

### ISSUE THREAD

**Issue by jeswheel** [rjournal/rjtools#132]
A recent change (3950d84d9adf7091705385e9cb8d1444feb05e6f) appears to have broken the checks for me. The change looks for the end of the main-body text by searching in the TeX file for a section called "References". By default, this section doesn't exists. Based on the template `.Rmd` (after adjusting for this workaround https://github.com/rjournal/rjtools/issues/128#issuecomment-2495784167) , the header may look something like this:  

```
title: "ToOoOlTiPs: An R Package for Customizable Tooltips in Interactive Graphics"
date: "2022-11-09"
abstract: >
  An abstract of less than 150 words.
draft: true
author:  
  - name: Quietest Quokka
    affiliation: University of Little Mates
    address:
    - Department of Letter Q
    - Somewhere, Australia
    url: https://www.britannica.com/animal/quokka
    orcid: 0000-1721-1511-1101
    email:  qquo@ulm.edu
  - name: Bounciest Bilby
    affiliation:
    - University of Little Mates
    - University of Aussie Animals
    address:
    - Department of Letter Q, Somewhere, Australia
    - Department of Marsupials, Somewhere, Australia
    url: https://www.britannica.com/animal/bilby
    email: bbil@ulm.edu
    orcid: 0000-0002-0912-0225
type: package
output: 
  rjtools::rjournal_pdf_article:
    toc: no
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib
---
```

Creating a document with this header and bibliography,  there is no references section created. Instead, the end of the TeX file created looks like this: 

```
...
[76] "\\section{Summary}\\label{summary}"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 [77] ""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 [78] "We have displayed various tooltips that are available in the package \\pkg{ToOoOlTiPs}."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 [79] ""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 [80] "\\bibliography{RJreferences.bib}"                                                         
```

This is exactly what the original code was meant to search for, prior to 3950d84d9adf7091705385e9cb8d1444feb05e6f. That is, it's looking for the text `\\bibliography{...}` to find where the main body ends in order to perform a spell check. It appears to me that this change does not work for all output types, operating systems, or reference styles. I assume that the change did fix an issue that may arise, for instance, if you manually create the References section and entries. However---unless my setup is uniquely the problem---it appears to cause an issue if the bibliography is created automatically using a `.bib` file. 

Session Info: 
```
R version 4.4.2 (2024-10-31)
Platform: x86_64-apple-darwin20
Running under: macOS Sequoia 15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Detroit
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rjtools_1.0.16

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5         cli_3.6.3           knitr_1.48          rlang_1.1.4        
 [5] xfun_0.46           stringi_1.8.4       purrr_1.0.2         hunspell_3.0.5     
 [9] glue_1.8.0          yesno_0.1.3         htmltools_0.5.8.1   brio_1.1.5         
[13] rmarkdown_2.27      evaluate_0.24.0     fastmap_1.2.0       yaml_2.3.10        
[17] lifecycle_1.0.4     BiocManager_1.30.25 stringr_1.5.1       compiler_4.4.2     
[21] fs_1.6.5            Rcpp_1.0.13-1       testthat_3.2.1.1    rstudioapi_0.16.0  
[25] digest_0.6.37       R6_2.5.1            magrittr_2.0.3      tools_4.4.2        
```
