### ISSUE TITLE
Authors with multiple affiliations

### ISSUE THREAD

**Issue by LiNk-NY** [rjournal/rjtools#65]
Hi @huizezhang-sherry 
Is it possible to have multiple affiliations per author? 
I did not see a straight-forward example of that. 
Thank you for your help. 
Best,
Marcel

https://github.com/rjournal/rjtools/blob/5e9412fc8c459926bab307cb3b6c8aca3462a7e2/inst/rmarkdown/templates/rjournal/skeleton/skeleton.Rmd#L10-L13

**Comment by huizezhang-sherry** [comment]
Hi Marcel, You can do the following: 

```
author:      
    - name: Quietest Quokka
    affiliation: 
    - University of Little Mates
    - University of Aussie Animals
    address:
    - Department of Letter Q, Somewhere, Australia
    - Department of Marsupials, Somewhere, Australia
    url: https://www.britannica.com/animal/quokka
    orcid: 0000-1721-1511-1101
    email:  qquo@ulm.edu
```

-Sherry
