### ISSUE TITLE
Combine rows in table

### ISSUE THREAD

**Issue by JiangmeiRubyXiong** [rjournal/rjtools#67]
I tried to combine rows in a table to reduce redundancy using KableExtra, but I always get an error when knitting the table. How should I add LaTeX dependency?

In YAML setting, I used:
```
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    number_sections: false
    extra_dependencies: ["multirow"]
```

Table Code: 
```{r}
collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                 C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                 C3 = 1:15,
                 C4 = sample(c(0,1), 15, replace = TRUE))
kbl(collapse_rows_dt, align = "c") %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```
and the error message is

```
! Undefined control sequence.
l.40  & \multirow
                 [t]{-7}{*}{\centering\arraybackslash c} & 7 & 0\\
---
```

Any way to get around this? Or do I have to switch back to latex?
