### ISSUE TITLE
While knitting to rjournal_web_article, I get this error: "! LaTeX Error: Environment longtable undefined."

### ISSUE THREAD

**Issue by technOslerphile** [rjournal/rjtools#73]
I am trying to compile an article for R journal using the rjtools package. I have a table in the .rmd file and without the table, the knitting works just fine. But when I include the table, the following error is seen in RJwrapper.log file:

```
! LaTeX Error: Environment longtable undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.74 \begin{longtable}
```
I have tried to add a new preamble.tex file explictly stating `\usepackage{longtable}` in the tex file, but this didn't work out.

```
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    includes:
      in_header: preamble.tex
```
Can someone help me fix this issue?
